config/routes.rb
Mongoblog::Application.routes.draw do
  
  get "microposts/create"
  get "microposts/destroy"
  root "static_pages#home"

  get "home" => "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]

  get "signup" => "users#new"
  get "signin" => "sessions#new"
  get "signout" => "sessions#destroy"
  
end

app/models/micropost.rb
class Micropost
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated

  field :content, type: String
  field :user_id, type: Integer

  index({ user_id: 1 , created_at: 1})

  belongs_to :user

  #default_scoped order_by(:created_at => :desc)

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated

  field :firstname, type: String
  field :lastname, type: String
  field :password_digest, type: String
  field :email, type: String 
  field :admin, type: Boolean, default: false
  
  index({ email: 1 }, { unique: true })

  has_many :microposts, dependent: :destroy
  
  before_save { self.email = email.downcase }
  has_secure_password


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :firstname, presence: true, length: { maximum: 50 }
  validates :lastname, presence: true, length: { maximum: 50 }
  
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    redirect_to root_url
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content)
    end
    
    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.where(email: params[:session][:email].downcase).first
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash[:error] = 'Invalid email/password combination' 
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @micropost = current_user.microposts.build if session[:user_id]
    @feed_items = current_user.microposts.paginate(page: params[:page]) if session[:user_id]
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    #@users = User.all
     @users = User.paginate(page: params[:page], :per_page => 2)
  end
  
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page],:per_page => 2)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Ruby and MongoDb App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:firstname,:lastname,:email,:password,:password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  #returns the full title on a per-page basis
  def full_title(page_title)
    base_title = "Rails and MongoDb"
    if page_title.blank?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user._id
    session[:firstname] = user.firstname
    flash[:notice] = "You are now logged in"
    self.current_user = user
  end


  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_user?(user)
    user == current_user
  end

   # def signed_in?
   #   !current_user.nil?
   # end

  def sign_out
    session[:user_id] = nil
    session[:firstname] = nil
    self.current_user = nil
    flash[:notice] = "Logout successful"
  end

  def signed_in_user
   redirect_to signin_url, notice: "Please sign in." unless session[:user_id]
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.firstname, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Mukesh Thakur
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<section class="container">
        <!-- row 1: navigation -->
    <div class="row">
        <nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse" >
                    <span class="src-only"></span>   
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Rails Mongo</a>
            </div> 
            <div class="collapse navbar-collapse" id="collapse">
                <ul class="nav navbar-nav pull-right">
                    <li> <%= link_to "Home", home_path %> </li>
                    <li> <%= link_to "Help", help_path %> </li>

                    <% if session[:user_id] %>
                        <li><%= link_to "Users", users_path %></li>
                        <li id="fat-menu" class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Account <b class="caret"></b>
                          </a>
                          <ul class="dropdown-menu">
                            <li><%= link_to "Profile", current_user %></li>
                            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                            <li class="divider"></li>
                            <li>
                              <%= link_to "Sign out", signout_path %>
                            </li>
                          </ul>
                        </li>
                    <% else %>
                        <li><%= link_to "Sign in", signin_path %></li>
                    <% end %>
                </ul>
            </div>
        </nav> 
    </div> <!-- navigation -->
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(@title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
 
</head>
<body>
	
	<%= render 'layouts/header' %>
	<div class="container">
		
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <% if current_user?(micropost.user) %>
    <%= link_to "delete", micropost, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: micropost.content %>
  <% end %>
</li>

app/views/microposts/create.html.erb
<h1>Microposts#create</h1>
<p>Find me in app/views/microposts/create.html.erb</p>

app/views/shared/_error_messages.html.erb
<% flash.each do |name,message|%>
	<script>
	  var msg="<%= message %>";
	  toastr.info(msg);
	</script>
<% end %>

<% if @micropost %>
	<% @micropost.errors.full_messages.each do |error|%>
		<script>
		  var msg="<%= error %>";
		  toastr.error(msg)
		</script>
	<% end %>
<% end %>

<% if @user %>
	<% @user.errors.full_messages.each do |error|%>
		<script>
		  var msg="<%= error %>";
		  toastr.error(msg)
		</script>
	<% end %>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.firstname, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
   <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>

  <%= render 'shared/error_messages' %>
  
  <div class="form-group">
    <div class="col col-sm-12">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
   </div>
  </div>

  <div class="form-group">
    <div class="col col-sm-12">
      <%= f.submit "Post",  :class => "btn btn-primary " %>
    </div>
  </div>

<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user), current_user %>
<h1>
  <%= current_user.firstname %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>

app/views/static_pages/about.html.erb
<% @title = "About" %>
<h1>About Us</h1>
<p>
  This is Ruby and Mongo Db app.
</p>

app/views/static_pages/contact.html.erb
<% @title = "Contact" %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% @title = "Home" %>
<% if session[:user_id] %>
<section class="row">
  <div class="col col-sm-5">
    <aside>
      <section>
        <%= render 'shared/user_info' %>
      </section>
  
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
  </div>
  <div class="col col-sm-7">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
</section>
<% else %>
  <div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user ,:html => {:class => "form-horizontal"} do |f| %>

  <div class="form-group">
    <%= f.label(:firstname, :class => "col-sm-2 control-label") %>
    <div class="col-sm-5">
      <%= f.text_field(:firstname, :class => "form-control", :placeholder => "Chuck")%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label(:lastname, :class => "col-sm-2 control-label") %>
    <div class="col-sm-5">
      <%= f.text_field(:lastname, :class => "form-control", :placeholder => "Chuck")%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label(:email, :class => "col-sm-2 control-label") %>
    <div class="col-sm-5">
      <%= f.text_field(:email, :class => "form-control", :placeholder => "chuck@norris.com")%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label(:password, :class => "col-sm-2 control-label") %>
    <div class="col-sm-5">
      <%= f.password_field(:password, :class => "form-control", :placeholder => "*********")%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label(:password_confirmation, "Confirmation", :class => "col-sm-2 control-label") %>
    <div class="col-sm-5">
      <%= f.password_field(:password_confirmation, :class => "form-control", :placeholder => "*********")%>
    </div>
  </div>


  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Create my account", :class => "btn btn-primary " %>
    </div>
  </div>

<% end %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user %>
	<%= link_to user.firstname, user %>
	<% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% @title = "Edit user" %>
<h1>Update your profile</h1>

<%= form_for @user ,:html => {:class => "form-horizontal"} do |f| %>

  <%= render 'shared/error_messages' %> 

  <div class="form-group">
    <%= f.label(:firstname, :class => "col-sm-2 control-label") %>
    <div class="col-sm-5">
      <%= f.text_field(:firstname, :class => "form-control", :placeholder => "Chuck")%>
    </div>
  </div>

    <div class="form-group">
      <%= f.label(:lastname, :class => "col-sm-2 control-label") %>
      <div class="col-sm-5">
        <%= f.text_field(:lastname, :class => "form-control", :placeholder => "Chuck")%>
      </div>
    </div>

  <div class="form-group">
    <%= f.label(:email, :class => "col-sm-2 control-label") %>
    <div class="col-sm-5">
      <%= f.text_field(:email, :class => "form-control", :placeholder => "chuck@norris.com")%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label(:password, :class => "col-sm-2 control-label") %>
    <div class="col-sm-5">
      <%= f.password_field(:password, :class => "form-control", :placeholder => "*********")%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label(:password_confirmation, "Confirmation", :class => "col-sm-2 control-label") %>
    <div class="col-sm-5">
      <%= f.password_field(:password_confirmation, :class => "form-control", :placeholder => "*********")%>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Save changes", :class => "btn btn-primary " %>
    </div>
  </div>

  <div class="col-sm-offset-2 col-sm-10">
    <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails">change</a>
  </div>
  
<% end %>

app/views/users/index.html.erb
<% @title =  'All users' %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %> <!--! this will call the user partial and automatically iterate the users object -->
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% @title = "Sign up" %>
<h1>Sign up</h1>

<%= render 'shared/error_messages' %>

<div class="formwrapper">
	<h4 class="text-center"></h4>
	<%= render 'form' %>
</div>


<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% @title = @user.firstname %>
 <%= render 'shared/error_messages' %> 

<aside class="row">
	<section class="col col-lg-3">
		<h1>
			<%= gravatar_for @user %>
			<%= @user.firstname %>	
		</h1>
	</section>


	<div class="col col-lg-9 pull-right">
		<% if @user.microposts.any? %>
		  <h3>Microposts (<%= @user.microposts.count %>)</h3>
		  <ol class="microposts">
		    <%= render @microposts %>
		  </ol>
		  <%= will_paginate @microposts %>
		<% end %>
	</div>
</aside>